# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
version: 2
jobs:
  build:
    docker:
      # Image to use as build runner.
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build 1"
          command: |
            mkdir dir1 && mv sleep.sh dir1/ && cd dir1 && ./sleep.sh
            # docker build -t eugenesia/circleci-debug:1 .
      - run:
          name: "Build 2"
          command: |
            docker build -t eugenesia/circleci-debug:2 .

